version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=http
      - ASSET_HUB_URL=ws://127.0.0.1:50002
      - RELAY_CHAIN_URL=ws://127.0.0.1:63168
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped 